### ISSUE TITLE
Semicolons not respected

### ISSUE THREAD

**Issue by 132ikl** [blindFS/topiary-nushell#4]
Lines with semicolons are incorrectly formatted:

Source:
```nushell
foo; bar
```

Formatted:
```nushell
foo;
bar
```

**Comment by blindFS** [comment]
Caused by [this line](https://github.com/blindFS/topiary-nushell/blob/b6d8484d684dbc990e171d8691705cf92c1917e3/languages/nushell.scm#L185), removing it now probably will cause other issues.

With the latest grammar however, this line is removed, only

```scheme
(pipeline
  "|" @prepend_space @append_space @prepend_empty_softline
)
```

remained to handle newlines within pipelines, this should be fixed then.

**Comment by blindFS** [comment]
I think it's fixed now, current behavior:

source:

```nushell
foo; bar

foo;
bar

foo
bar
```

formatted: same as the source

**Comment by blindFS** [comment]
@132ikl I’m going to close this for now, but feel free to reopen it if anything else comes up.
